version: '3.8'

services:
  database_addcode:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-adcode_admin}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: ${DB_NAME:-adcode_database}
    ports:
      - "5333:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    secrets:
      - db_password

volumes:
  postgres_data:
    driver: local

networks:
  backend:
    driver: bridge

secrets:
  db_password:
    file: ./secrets/db_password.txt